name: Flight price check

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  check-flights:
    runs-on: ubuntu-latest

    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Check flights
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          TRAVELPAYOUTS_TOKEN: ${{ secrets.TRAVELPAYOUTS_TOKEN }}
          PRICE_LIMIT: "25000"
          CHECK_MINUTES: "15"
        run: python bot.py
#      - name: Check Antalya
#        env:
#            TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
#            TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
#            TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
#            TRAVELPAYOUTS_TOKEN: ${{ secrets.TRAVELPAYOUTS_TOKEN }}
#        run: python antalya.py
     
